<?php

namespace App\Services;

class FilterRegistry
{
    public static function getFilters(): array
    {
        // Try to fetch from database first
        try {
            $dbFilters = \App\Models\FilterRegistry::where('is_active', true)
                ->orderBy('sort_order', 'asc')
                ->get();

            if ($dbFilters->isNotEmpty()) {
                return $dbFilters->map(function ($filter) {
                    return [
                        'id' => $filter->id,
                        'label' => $filter->label,
                        'group' => $filter->group_name,
                        'applies_to' => $filter->applies_to,
                        'type' => $filter->type,
                        'input' => $filter->input_type,
                        'data_source' => $filter->data_source,
                        'fields' => $filter->fields,
                        'search' => $filter->search_config,
                        'filtering' => $filter->filtering_config,
                        'aggregation' => $filter->aggregation_config,
                        'preloaded_values' => $filter->preloaded_values,
                        'range' => $filter->range_config,
                        'hint' => $filter->hint,
                        'sort_order' => $filter->sort_order,
                        'active' => $filter->is_active,
                    ];
                })->toArray();
            }
        } catch (\Exception $e) {
            // Table might not exist yet or other migration issues
        }

        // Fallback to hardcoded list if DB is empty or fails
        return self::defaultFilters();
    }

    public static function defaultFilters(): array
    {
        return [
            // --- Company Filters ---
            [
                'id' => 'company_name',
                'label' => 'Company Name',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'text',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['company'],
                    'contact' => ['company'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['company']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true],
                'sort_order' => 10,
                'active' => true,
            ],
            [
                'id' => 'company_domain',
                'label' => 'Company Domain',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['website'],
                    'contact' => ['website'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['website']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true],
                'sort_order' => 20,
                'active' => true,
            ],
            [
                'id' => 'business_category',
                'label' => 'Business Category',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['business_category'],
                    'contact' => ['company_obj.business_category'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['business_category']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 32,
                'active' => true,
            ],
            [
                'id' => 'industry',
                'label' => 'Industry',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['industry', 'business_category'],
                    'contact' => ['company_obj.industry', 'company_obj.business_category'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['industry', 'business_category']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 33,
                'active' => true,
            ],
            [
                'id' => 'sic_codes',
                'label' => 'SIC Codes',
                'group' => 'Company',
                'applies_to' => ['company'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['sic_code', 'sic_codes', 'naics_code', 'naics_codes'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['sic_code', 'sic_codes', 'naics_code', 'naics_codes']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'preloaded_values' => [
                    ['id' => '7372', 'name' => '7372 - Prepackaged Software', 'count' => null],
                    ['id' => '7371', 'name' => '7371 - Computer Programming Services', 'count' => null],
                    ['id' => '7373', 'name' => '7373 - Computer Integrated Systems Design', 'count' => null],
                    ['id' => '8742', 'name' => '8742 - Management Consulting Services', 'count' => null],
                    ['id' => '7379', 'name' => '7379 - Computer Related Services', 'count' => null],
                ],
                'sort_order' => 34,
                'active' => true,
            ],
            [
                'id' => 'keywords',
                'label' => 'Keywords',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['keywords'],
                    'contact' => ['company_obj.keywords'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['keywords']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true, 'split_on_comma' => true],
                'sort_order' => 36,
                'active' => true,
            ],
            [
                'id' => 'technologies',
                'label' => 'Technologies',
                'group' => 'Technology',
                'applies_to' => ['company'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['company_technologies'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['company_technologies']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true, 'split_on_comma' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'preloaded_values' => [
                    ['id' => 'Microsoft', 'name' => 'Microsoft', 'count' => null],
                    ['id' => 'Amazon AWS', 'name' => 'Amazon AWS', 'count' => null],
                    ['id' => 'Google Cloud', 'name' => 'Google Cloud', 'count' => null],
                    ['id' => 'Outlook', 'name' => 'Outlook', 'count' => null],
                    ['id' => 'Gmail', 'name' => 'Gmail', 'count' => null],
                    ['id' => 'Salesforce', 'name' => 'Salesforce', 'count' => null],
                    ['id' => 'HubSpot', 'name' => 'HubSpot', 'count' => null],
                    ['id' => 'WordPress', 'name' => 'WordPress', 'count' => null],
                ],
                'sort_order' => 50,
                'active' => true,
            ],
            [
                'id' => 'employee_count',
                'label' => 'Employee Count',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'range',
                'input' => 'range',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['employee_count'],
                ],
                'filtering' => ['mode' => 'range'],
                'range' => ['min' => 0, 'max' => 100000, 'step' => 10], // Explicit range for UI
                'sort_order' => 55,
                'active' => true,
            ],
            [
                'id' => 'annual_revenue',
                'label' => 'Annual Revenue',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'range',
                'input' => 'range',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['annual_revenue'],
                ],
                'filtering' => ['mode' => 'range'],
                'range' => ['min' => 0, 'max' => 1000000000, 'step' => 100000, 'unit' => 'currency'],
                'sort_order' => 58,
                'active' => true,
            ],
            [
                'id' => 'founded_year',
                'label' => 'Founded Year',
                'group' => 'Company',
                'applies_to' => ['company', 'contact'],
                'type' => 'range',
                'input' => 'range',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['founded_year'],
                ],
                'filtering' => ['mode' => 'range'],
                'range' => ['min' => 1900, 'max' => (int) date('Y'), 'step' => 1, 'unit' => 'year'],
                'sort_order' => 59,
                'active' => true,
            ],
            [
                'id' => 'total_funding',
                'label' => 'Total Funding',
                'group' => 'Funding',
                'applies_to' => ['company', 'contact'],
                'type' => 'range',
                'input' => 'range',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['funding.total_funding'],
                    'contact' => ['company_obj.funding.total_funding'],
                ],
                'filtering' => ['mode' => 'range'],
                'range' => ['min' => 0, 'max' => 1000000000, 'step' => 100000, 'unit' => 'usd'],
                'sort_order' => 60,
                'active' => true,
            ],
            [
                'id' => 'has_funding',
                'label' => 'Has Funding',
                'group' => 'Funding',
                'applies_to' => ['company'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['funding.total_funding'],
                ],
                'filtering' => ['mode' => 'range', 'has_funding_check' => true],
                'sort_order' => 61,
                'active' => true,
            ],

            // --- Company Location ---
            [
                'id' => 'company_country',
                'label' => 'Country',
                'group' => 'Company Location',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['location.country'],
                    'contact' => ['location.country'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['location.country']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'sort_order' => 60,
                'active' => true,
            ],
            [
                'id' => 'company_state',
                'label' => 'State',
                'group' => 'Company Location',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['location.state'],
                    'contact' => ['location.state'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['location.state']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'sort_order' => 62,
                'active' => true,
            ],
            [
                'id' => 'company_city',
                'label' => 'City',
                'group' => 'Company Location',
                'applies_to' => ['company', 'contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['location.city'],
                    'contact' => ['location.city'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['location.city']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'sort_order' => 64,
                'active' => true,
            ],
            [
                'id' => 'postal_code',
                'label' => 'Postal Code',
                'group' => 'Company Location',
                'applies_to' => ['company'],
                'type' => 'keyword',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'company' => ['location.postal_code'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['location.postal_code']],
                'filtering' => ['mode' => 'terms'],
                'sort_order' => 66,
                'active' => true,
            ],

            // --- Contact Filters ---
            [
                'id' => 'first_name',
                'label' => 'First Name',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'text',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['first_name'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['first_name']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true],
                'sort_order' => 200,
                'active' => true,
            ],
            [
                'id' => 'last_name',
                'label' => 'Last Name',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'text',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['last_name'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['last_name']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true],
                'sort_order' => 210,
                'active' => true,
            ],
            [
                'id' => 'full_name',
                'label' => 'Full Name',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'text',
                'input' => 'text',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['full_name'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['full_name']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true],
                'sort_order' => 215,
                'active' => true,
            ],
            [
                'id' => 'job_title',
                'label' => 'Job Title',
                'group' => 'Role',
                'applies_to' => ['contact'],
                'type' => 'text',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['title'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['title']],
                'filtering' => ['mode' => 'match', 'supports_exclusion' => true],
                'hint' => 'Tip: Use "quotation marks" for absolute match',
                'sort_order' => 220,
                'active' => true,
            ],
            [
                'id' => 'seniority',
                'label' => 'Seniority',
                'group' => 'Role',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'checkbox_list',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['seniority'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['seniority']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => true, 'size' => 50],
                'preloaded_values' => [
                    ['id' => 'owner', 'name' => 'Owner', 'count' => null],
                    ['id' => 'founder', 'name' => 'Founder', 'count' => null],
                    ['id' => 'partner', 'name' => 'Partner', 'count' => null],
                    ['id' => 'vp', 'name' => 'VP', 'count' => null],
                    ['id' => 'director', 'name' => 'Director', 'count' => null],
                    ['id' => 'head', 'name' => 'Head', 'count' => null],
                    ['id' => 'manager', 'name' => 'Manager', 'count' => null],
                    ['id' => 'senior', 'name' => 'Senior', 'count' => null],
                    ['id' => 'entry', 'name' => 'Entry', 'count' => null],
                    ['id' => 'intern', 'name' => 'Intern', 'count' => null],
                ],
                'sort_order' => 230,
                'active' => true,
            ],
            [
                'id' => 'departments',
                'label' => 'Departments',
                'group' => 'Role',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'checkbox_list',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['departments'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['departments']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => false],
                'aggregation' => ['enabled' => true, 'size' => 50],
                'preloaded_values' => [
                    ['id' => 'sales', 'name' => 'Sales', 'count' => null],
                    ['id' => 'marketing', 'name' => 'Marketing', 'count' => null],
                    ['id' => 'engineering', 'name' => 'Engineering & Technical', 'count' => null],
                    ['id' => 'c_suite', 'name' => 'C-Suite', 'count' => null],
                    ['id' => 'operations', 'name' => 'Operations', 'count' => null],
                    ['id' => 'finance', 'name' => 'Finance', 'count' => null],
                    ['id' => 'human_resources', 'name' => 'Human Resources', 'count' => null],
                    ['id' => 'product', 'name' => 'Product', 'count' => null],
                    ['id' => 'legal', 'name' => 'Legal', 'count' => null],
                    ['id' => 'education', 'name' => 'Education', 'count' => null],
                ],
                'sort_order' => 240,
                'active' => true,
            ],

            // --- Contact Location ---
            [
                'id' => 'contact_country',
                'label' => 'Contact Country',
                'group' => 'Contact Location',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['location.country'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['location.country']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 100],
                'sort_order' => 250,
                'active' => true,
            ],
            [
                'id' => 'contact_state',
                'label' => 'Contact State',
                'group' => 'Contact Location',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['location.state'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['location.state']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 50],
                'sort_order' => 252,
                'active' => true,
            ],
            [
                'id' => 'contact_city',
                'label' => 'Contact City',
                'group' => 'Contact Location',
                'applies_to' => ['contact'],
                'type' => 'keyword',
                'input' => 'multi_select',
                'data_source' => 'elasticsearch',
                'fields' => [
                    'contact' => ['location.city'],
                ],
                'search' => ['enabled' => true, 'suggest_fields' => ['location.city']],
                'filtering' => ['mode' => 'terms', 'supports_exclusion' => true],
                'aggregation' => ['enabled' => true, 'size' => 50],
                'sort_order' => 254,
                'active' => true,
            ],

            // --- Boolean Filters ---
            [
                'id' => 'work_email_exists',
                'label' => 'Work Email Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['emails.email'],
                ],
                'filtering' => ['mode' => 'exists'],
                'sort_order' => 250,
                'active' => true,
            ],
            [
                'id' => 'mobile_number_exists',
                'label' => 'Mobile Number Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['phone_numbers.phone_number'],
                ],
                'filtering' => ['mode' => 'exists'],
                'sort_order' => 270,
                'active' => true,
            ],
            [
                'id' => 'direct_number_exists',
                'label' => 'Direct Number Exists',
                'group' => 'Personal',
                'applies_to' => ['contact'],
                'type' => 'boolean',
                'input' => 'toggle',
                'data_source' => 'direct',
                'fields' => [
                    'contact' => ['phone_numbers.phone_number'],
                ],
                'filtering' => ['mode' => 'exists'],
                'sort_order' => 280,
                'active' => true,
            ],
        ];
    }
}